// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {account} from '../models';
import {context} from '../models';

export function GetAccountInfo():Promise<account.Account|Error>;

export function IsAccount():Promise<boolean>;

export function IsAccountSetting():Promise<boolean>;

export function WailsInit(arg1:context.Context):Promise<Error>;
