// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function WailsInit(arg1) {
  return window['go']['app']['Account']['WailsInit'](arg1);
}

export function GetAccountInfo() {
  return window['go']['app']['Account']['GetAccountInfo']();
}

export function IsAccount() {
  return window['go']['app']['Account']['IsAccount']();
}

export function IsAccountSetting() {
  return window['go']['app']['Account']['IsAccountSetting']();
}

export function SaveOrderIndex(arg1) {
  window['go']['app']['Account']['SaveOrderIndex'](arg1);
}
