// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueryApplicationById(arg1) {
  return window['go']['app']['Application']['QueryApplicationById'](arg1);
}

export function ReconnectionProLink(arg1) {
  return window['go']['app']['Application']['ReconnectionProLink'](arg1);
}

export function RefreshGraphDeployJob(arg1) {
  return window['go']['app']['Application']['RefreshGraphDeployJob'](arg1);
}

export function UpdateThinkingTime(arg1, arg2) {
  return window['go']['app']['Application']['UpdateThinkingTime'](arg1, arg2);
}

export function WailsInit(arg1) {
  return window['go']['app']['Application']['WailsInit'](arg1);
}

export function AddApplication(arg1) {
  return window['go']['app']['Application']['AddApplication'](arg1);
}

export function DeleteApplication(arg1) {
  return window['go']['app']['Application']['DeleteApplication'](arg1);
}

export function UpdateApplicationIncome(arg1, arg2) {
  return window['go']['app']['Application']['UpdateApplicationIncome'](arg1, arg2);
}

export function ApplicationList(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Application']['ApplicationList'](arg1, arg2, arg3, arg4);
}

export function UpdateApplication(arg1) {
  return window['go']['app']['Application']['UpdateApplication'](arg1);
}
