// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { v2 } from '../models';
import { application } from '../models';
import { context } from '../models';

export function AddApplication(arg1: v2.AddParam): Promise<v2.AddApplicationVo>;

export function ApplicationList(
  arg1: number,
  arg2: number,
  arg3: string,
  arg4: number,
): Promise<application.PageApplicationVo>;

export function DeleteApplication(arg1: number): Promise<boolean>;

export function QueryApplicationById(arg1: number): Promise<application.ApplyVo>;

export function ReconnectionProLink(arg1: number): Promise<boolean>;

export function RefreshGraphDeployJob(arg1: number): Promise<Error>;

export function UpdateApplication(arg1: application.UpdateApplicationParam): Promise<boolean>;

export function UpdateApplicationIncome(arg1: number, arg2: number): Promise<boolean>;

export function UpdateThinkingTime(arg1: number, arg2: number): Promise<boolean>;

export function WailsInit(arg1: context.Context): Promise<Error>;
