// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveDeployInfo(arg1, arg2) {
  return window['go']['app']['Deploy']['SaveDeployInfo'](arg1, arg2);
}

export function WailsInit(arg1) {
  return window['go']['app']['Deploy']['WailsInit'](arg1);
}

export function DeployTheGraph(arg1, arg2) {
  return window['go']['app']['Deploy']['DeployTheGraph'](arg1, arg2);
}

export function GetDeployInfo(arg1) {
  return window['go']['app']['Deploy']['GetDeployInfo'](arg1);
}

export function QueryGraphStatus(arg1) {
  return window['go']['app']['Deploy']['QueryGraphStatus'](arg1);
}
