// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { deploy } from '../models';
import { context } from '../models';

export function DeployTheGraph(arg1: deploy.DeployParams): Promise<boolean | Error>;

export function WailsInit(arg1: context.Context): Promise<Error>;
