// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { deploy } from '../models';
import { context } from '../models';

export function DeployTheGraph(arg1: number, arg2: string): Promise<boolean>;

export function GetDeployInfo(arg1: number): Promise<deploy.DeployParameter>;

export function QueryGraphStatus(arg1: number, arg2: Array<string>): Promise<number>;

export function SaveDeployInfo(arg1: number, arg2: string): Promise<boolean>;

export function WailsInit(arg1: context.Context): Promise<Error>;
