// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeployTheGraph(arg1) {
  return window['go']['app']['Deploy']['DeployTheGraph'](arg1);
}

export function WailsInit(arg1) {
  return window['go']['app']['Deploy']['WailsInit'](arg1);
}
