// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { context } from '../models';
import { graph } from '../models';

export function WailsInit(arg1: context.Context): Promise<Error>;

export function CliLink(arg1: number): Promise<number | Error>;

export function QueryApplyAndParams(arg1: number): Promise<graph.GraphParameterVo | Error>;
