// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CliLink(arg1) {
  return window['go']['app']['Graph']['CliLink'](arg1);
}

export function GraphConnect() {
  return window['go']['app']['Graph']['GraphConnect']();
}

export function GraphRules() {
  return window['go']['app']['Graph']['GraphRules']();
}

export function GraphStart(arg1) {
  return window['go']['app']['Graph']['GraphStart'](arg1);
}

export function QueryApplyAndParams(arg1) {
  return window['go']['app']['Graph']['QueryApplyAndParams'](arg1);
}

export function WailsInit(arg1) {
  return window['go']['app']['Graph']['WailsInit'](arg1);
}
