// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Set(arg1: string, arg2: string): void;

export function Delete(arg1: string): void;

export function Get(arg1: string): Promise<string>;
