// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Set(arg1, arg2) {
  return window['go']['app']['KeyStorage']['Set'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['app']['KeyStorage']['Delete'](arg1);
}

export function Get(arg1) {
  return window['go']['app']['KeyStorage']['Get'](arg1);
}
