// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLinkStatus() {
  return window['go']['app']['P2p']['GetLinkStatus']();
}

export function IsP2PSetting() {
  return window['go']['app']['P2p']['IsP2PSetting']();
}

export function JudgeP2pReconnection() {
  return window['go']['app']['P2p']['JudgeP2pReconnection']();
}

export function Link(arg1, arg2) {
  return window['go']['app']['P2p']['Link'](arg1, arg2);
}

export function WailsInit(arg1) {
  return window['go']['app']['P2p']['WailsInit'](arg1);
}

export function WailsShutdown() {
  window['go']['app']['P2p']['WailsShutdown']();
}

export function CloseLink(arg1) {
  return window['go']['app']['P2p']['CloseLink'](arg1);
}
