// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { v2 } from '../models';

export function GetQueueInfo(arg1: number): Promise<v2.QueueInfo | Error>;
