// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function WailsInit(arg1) {
  return window['go']['app']['Resource']['WailsInit'](arg1);
}

export function GetResources() {
  return window['go']['app']['Resource']['GetResources']();
}
