// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {resource} from '../models';

export function WailsInit(arg1:context.Context):Promise<Error>;

export function GetResources():Promise<Array<resource.Resource>|Error>;
