// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Setting(arg1, arg2) {
  return window['go']['app']['Setting']['Setting'](arg1, arg2);
}

export function WailsInit(arg1) {
  return window['go']['app']['Setting']['WailsInit'](arg1);
}

export function GetSetting() {
  return window['go']['app']['Setting']['GetSetting']();
}

export function InitP2pSetting() {
  return window['go']['app']['Setting']['InitP2pSetting']();
}
