// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStateInfo(arg1) {
  return window['go']['app']['State']['GetStateInfo'](arg1);
}
