// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { state } from '../models';

export function GetStateInfo(arg1: string): Promise<state.Info | Error>;
