// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveWallet(arg1, arg2, arg3) {
  return window['go']['app']['Wallet']['SaveWallet'](arg1, arg2, arg3);
}

export function WailsInit(arg1) {
  return window['go']['app']['Wallet']['WailsInit'](arg1);
}

export function DeleteWallet() {
  return window['go']['app']['Wallet']['DeleteWallet']();
}

export function GetWalletInfo() {
  return window['go']['app']['Wallet']['GetWalletInfo']();
}
