// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function QueryGraphStatus(arg1) {
  return window['go']['app']['Application']['QueryGraphStatus'](arg1);
}

export function UpdateApplication(arg1) {
  return window['go']['app']['Application']['UpdateApplication'](arg1);
}

export function WailsInit(arg1) {
  return window['go']['app']['Application']['WailsInit'](arg1);
}

export function AddApplication(arg1) {
  return window['go']['app']['Application']['AddApplication'](arg1);
}

export function ApplicationList(arg1, arg2, arg3, arg4) {
  return window['go']['app']['Application']['ApplicationList'](arg1, arg2, arg3, arg4);
}

export function DeleteApplication(arg1) {
  return window['go']['app']['Application']['DeleteApplication'](arg1);
}

export function DeleteGraphAndParams(arg1) {
  return window['go']['app']['Application']['DeleteGraphAndParams'](arg1);
}

export function QueryApplicationById(arg1) {
  return window['go']['app']['Application']['QueryApplicationById'](arg1);
}
