// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import { application } from '../models';
import { context } from '../models';

export function QueryGraphStatus(arg1: string): Promise<number | Error>;

export function UpdateApplication(arg1: application.Application): Promise<Error>;

export function WailsInit(arg1: context.Context): Promise<Error>;

export function AddApplication(arg1: application.Application): Promise<Error>;

export function ApplicationList(
  arg1: number,
  arg2: number,
  arg3: string,
  arg4: number,
): Promise<Array<application.Application> | Error>;

export function DeleteApplication(arg1: number): Promise<Error>;

export function DeleteGraphAndParams(arg1: number): Promise<Error>;

export function QueryApplicationById(arg1: number): Promise<application.Application | Error>;
